version: '3.8'

services:
  apache:
    build:
      context: ./apache
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
#      - app-network
      - shared-net

  springboot:
    build:
      context: ./app
    ports:
      - "8080:8080"
    networks:
#      - app-network
      - shared-net

networks:
  shared-net:
    external: true
#  app-network:
